[tool.poetry]
name = "auto-spa"
version = "0.1.0"
description = ""
authors = ["pvys <pvys20@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
web3 = "^5.25.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
